-- Store signed landing-page resume tokens for BodegaCRM email automation.
-- The token is generated by Rocoto Landing with LEAD_TOKEN_SECRET; do not store
-- raw secrets or accept unsigned lead ids in email links.

ALTER TABLE leads
  ADD COLUMN IF NOT EXISTS lead_token TEXT;

COMMENT ON COLUMN leads.lead_token IS
  'Signed Rocoto Landing resume token used for free pentest challenge links.';

CREATE UNIQUE INDEX IF NOT EXISTS idx_leads_lead_token_unique
  ON leads (lead_token)
  WHERE lead_token IS NOT NULL;
